### PR TITLE
Create additional tables

### PR DESCRIPTION
**Pull request by alexandralaudon**
Created the Salary & Title Migrations & Models. Also updated the refresh_database task to include salary & title refreshes.

### CODE REVIEW

**Comment by katekilian** [comment]
A few thoughts, all about the schema:
1. Can you explain what the function of `employee_no` is on both the Salaries and Titles tables?
2. The `from_date` and `to_date` on the aforementioned tables suggest that each Salary and Title is unique and is assigned to an employee, with a start and end date.  In my ideal world, I'd have a join table called Jobs, where an Employee has many Jobs, and a Job has a Salary and a Title (which could be reused over and over again).  The difficulty lies in Jobs belonging to many different Employees (i.e. let's imagine a world where you and I have the exact same job title with the same salary - do we have the same "job"?).

This is all a lot of hypothetical future thinking which might be completely unnecessary, as I know we didn't necessarily want to get into join tables yet because we wanted to keep it simple at first.  I'd just like you to clarify your vision of how the schema will work for now, and how it might progress later, given that everything is subject to change.

**Comment by alexandralaudon** [comment]
As a general rule, I'm not actually making this schema as a long term database that we will use. This is simply the first instance to determine front-end standards. We need to create many different schemas to ensure that this logic will work for a wide variety of possible databases. 

Again, I'm not thinking about joins. We first need to make this work for where statements, filters, etc. based on one table at a time. Joins will hopefully be the last piece of the puzzle. I just want to have multiple tables so we understand how to differentiate between all tables on the front-end. 

Do you still want me to fix this issue?

**Comment by alexandralaudon** [comment]
To clarify, long term, I was hoping to create a variety of schemas so we can make sure this logic would work in a number of different instances.

**Comment by katekilian** [comment]
Sure.  That'll be fine.  You've got a long term vision in mind, and I'm good with letting that play out as it will.

Approved!

**Pull request merged**
