### PR TITLE
Add Employees Structure

### PR DESCRIPTION
**Pull request by alexandralaudon**
This adds the necessary MVCs for Kate to start looking at the front-end. Also added rake task to recreate the DB anytime. I think it'll come in handy quite often.

Kate, what should I call the Controller & View since we'll be using this as our only controller? MainController? Main View? I see now that it would be best to rename these Controllers and Views with a generic name so I will do so in the next branch I create.

### CODE REVIEW

**Comment by katekilian** [comment]
Controller and View can be called Main or Generic for now - I think we'll become more clear as to its function (and if it should therefore be renamed) as the project evolves.  

Looks great overall - the only thing I'd suggest is to make the helper method `all_tables` private by adding `private` to the EmployeesController.

**Comment by alexandralaudon** [comment]
Interesting. I agree. I'll change that now.

**Comment by alexandralaudon** [comment]
Okay I've changed the method to private. Please approve.

**Comment by katekilian** [comment]
Approved!

**Pull request merged**
